export enum ErrorTypes {
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  REGION_IS_NOT_EXISTS = 'REGION_IS_NOT_EXISTS',
  ADDRESS_NOT_FULL = 'ADDRESS_NOT_FULL',
  PROVIDER_WITH_NPI_EXISTS = 'PROVIDER_WITH_NPI_EXISTS'
}

export enum FileErrorTypes {
  MAX_FILE_SIZE = 'MAX_FILE_SIZE',
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE'
}
